import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "@/providers/Socket";
import { TheProviders } from "@/providers/Theme";
import ThemeSwitch from "@/providers/ThemeSwitch";
import { AuthContextProvider } from "@/providers/ClientAuth";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <head>
        <title>ChatterBox - Connect and Chat in Real-Time.</title>
      </head>
      <body className={inter.className}>
        <SocketProvider>
          <AuthContextProvider>
            <TheProviders>
             <div className="relative justify-between items-center">
                <ThemeSwitch />                
                {children}
             </div>
            </TheProviders>
          </AuthContextProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
